# Generated by Django 5.1.3 on 2024-11-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('provider', 'Service Provider'), ('admin', 'Admin')], max_length=20),
        ),
    ]
