# Generated by Django 5.1.3 on 2024-12-01 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_serviceproviderprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='driving_license',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='experience',
            field=models.TextField(help_text='Please describe your professional experience in detail.'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
